spring:
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ssXXX"
    deserialization:
      fail-on-unknown-properties: false
    time-zone: "America/Sao_Paulo"
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/metrics
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Springdoc OpenApi 3.1 & Swagger 3
springdoc:
  packagesToScan: com.github.murilonerdx.skdemoparkapi.controller
  swagger-ui:
    path: /docs-park.html
  api-docs:
    path: /docs-park
